Setting up a new session...
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
{'data_root': './datasets/data', 'dataset': 'voc', 'num_classes': 21, 'model': 'deeplabv3plus_resnet50', 'separable_conv': False, 'output_stride': 16, 'test_only': False, 'save_val_results': False, 'total_itrs': 30000.0, 'lr': 0.01, 'lr_policy': 'poly', 'step_size': 10000, 'crop_val': False, 'batch_size': 2, 'val_batch_size': 4, 'crop_size': 512, 'ckpt': None, 'continue_training': False, 'loss_type': 'cross_entropy', 'gpu_id': '0', 'weight_decay': 0.0001, 'random_seed': 1, 'print_interval': 10, 'val_interval': 100, 'download': False, 'year': '2012', 'enable_vis': True, 'vis_port': '8097', 'vis_env': 'main', 'vis_num_samples': 8}
Device: cuda
Dataset: voc, Train set: 28, Val set: 7
[!] Retrain
Backend QtAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "E:\jupyter notebook\DeepLabV3Plus-Pytorch-master\main.py", line 409, in <module>
    main()
  File "E:\jupyter notebook\DeepLabV3Plus-Pytorch-master\main.py", line 342, in main
    outputs = model(images)
  File "C:\Users\91932\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\91932\.conda\envs\torch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 152, in forward
    for t in chain(self.module.parameters(), self.module.buffers()):
  File "C:\Users\91932\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1642, in parameters
    for name, param in self.named_parameters(recurse=recurse):
  File "C:\Users\91932\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1668, in named_parameters
    for elem in gen:
KeyboardInterrupt
